import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/layouts/Layout";
import ListingCard from "../components/listing/ListingCard";

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Marketplace for Villas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex items-center text-gray-100"></div>
      <div className="grid grid-cols-12 gap-5">
        <ListingCard />
        <ListingCard />
        <ListingCard />
        <ListingCard />
        <ListingCard />
      </div>
    </Layout>
  );
};

export default Home;
